version: "3.5"

services:
  laravel-proj:
    build:
      context: laravel-proj
      args:
        APP_ENV: production
    environment:
      APP_ENV: production
    volumes:
      - ./data/laravel/logs:/var/www/html/storage/logs
      # Useful for local development (to maintain *.lock files)
      - ./laravel-proj:/var/www/html
    ports:
      - 8000:80
